import fs from "node:fs";
import path from "node:path";

/**
 * Builds one review document interleaving each character's visual prose with the
 * redraw tag YAML that claims to derive from it, so both can be read side by side
 * in a single pass. Written to redraw/REVIEW.md, which is a build product.
 *
 * Only the sections that can legitimately source a tag are included: Appearance
 * (identity and outfits), Personality and Voice (expressions), and the single
 * anatomy sentence from Identity and life. Tastes, Motives, Skills, Agency and
 * Relationships never describe a portrait.
 */

const workspace = process.cwd();
const project = path.join(workspace, "projects/stardew-valley");
const tagDir = path.join(project, "redraw/tags");
const charDir = path.join(project, "source/characters");

const wanted = /^## (Appearance|Personality|Voice and behaviou?r)$/;

/** Split a profile into `## heading` sections, keeping the heading text as key. */
function sections(markdown: string): Map<string, string> {
  const found = new Map<string, string>();
  let heading = "";
  let body: string[] = [];
  for (const line of markdown.split("\n")) {
    if (line.startsWith("## ")) {
      if (heading) found.set(heading, body.join("\n").trim());
      heading = line;
      body = [];
    } else if (heading) body.push(line);
  }
  if (heading) found.set(heading, body.join("\n").trim());
  return found;
}

const characters = fs
  .readdirSync(tagDir)
  .filter((name) => name.endsWith(".yaml"))
  .map((name) => name.replace(/\.yaml$/, ""))
  .sort();

const out: string[] = [
  "# Redraw review — prose against tags",
  "",
  "Generated by `bun tools/redraw-review.ts`; do not edit. One section per",
  "character: the visual prose first, then the tag file that claims to derive from",
  "it. Everything a tag may legitimately come from is here, so a tag with no",
  "matching sentence is visible as an omission rather than hidden in another file.",
  "",
  `${characters.length} characters.`,
  "",
];

for (const character of characters) {
  const profile = fs.readFileSync(path.join(charDir, character, "content.md"), "utf8");
  const found = sections(profile);
  const anatomy = profile
    .split("\n")
    .filter((line) => /\bpenis\b|\bfutanari\b/i.test(line))
    .map((line) => line.trim());

  out.push(`---`, "", `# ${character}`, "");

  for (const [heading, body] of found)
    if (wanted.test(heading)) out.push(`## prose ${heading.slice(3)}`, "", body, "");

  if (anatomy.length) {
    out.push("## prose anatomy sentences", "");
    for (const line of anatomy) out.push(`> ${line}`, "");
  }

  out.push(`## tags \`redraw/tags/${character}.yaml\``, "", "```yaml");
  out.push(fs.readFileSync(path.join(tagDir, `${character}.yaml`), "utf8").trimEnd());
  out.push("```", "");
}

const outFile = path.join(project, "redraw/REVIEW.md");
fs.writeFileSync(outFile, `${out.join("\n").trimEnd()}\n`, "utf8");
const lines = out.join("\n").split("\n").length;
console.log(`wrote ${path.relative(workspace, outFile).split(path.sep).join("/")} — ${lines} lines`);
